#!/bin/bash

echo -e "\e[0;32m"
echo "███╗   ███╗ █████╗ ███████╗███████╗██╗   ██╗██████╗ ██████╗  █████╗ ████████╗███████╗"
echo "████╗ ████║██╔══██╗██╔════╝██╔════╝██║   ██║██╔══██╗██╔══██╗██╔══██╗╚══██╔══╝██╔════╝"
echo "██╔████╔██║███████║███████╗███████╗██║   ██║██████╔╝██║  ██║███████║   ██║   █████╗  "
echo "██║╚██╔╝██║██╔══██║╚════██║╚════██║██║   ██║██╔═══╝ ██║  ██║██╔══██║   ██║   ██╔══╝  "
echo "██║ ╚═╝ ██║██║  ██║███████║███████║╚██████╔╝██║     ██████╔╝██║  ██║   ██║   ███████╗"
echo "╚═╝     ╚═╝╚═╝  ╚═╝╚══════╝╚══════╝ ╚═════╝ ╚═╝     ╚═════╝ ╚═╝  ╚═╝   ╚═╝   ╚══════╝"
echo "           "

echo -e "\n"

if [ $UID -eq 0 ]; then
  echo "Root Access Granted"
  echo "STarting upgrade ...."
  echo "STarting with pacman ...."
  sudo pacman -Syu --noconfirm
  echo "PAcman update complete ."
  echo "STarting with yay ....."
  yay -Syu --noconfirm
else
  echo -e "\e[0;31m Run as Root "
fi
